# In this notebook, we are going to cover the most fundamental concepts of tensors using Tensor Flow
**Listen**, this lecture is about **TensorFlow**  
More specifically, we are going to cover:
* Introduction to tensors
* Manipulating tensors
*Tensors & NumPy
* Using @tf.function (a way to speed up your regular python functions)
* using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!






## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(7)
type(scalar)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector.ndim



1

In [ ]:
vector.ndim

1

In [ ]:
# Create a Matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]],
                             dtype = tf.float16 # specify the datatype parameter
                             )
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([
    [[0, 5, 2, 1, 2], [5, 2, 1, 4, 5]],
    [[2, 3, 4, 5, 6],[1, 3, 3, 3, 2]],
    [[1, 1, 3, 3, 4],[1, 1, 1, 1, 1]],
    [[1, 1, 1, 1, 1], [4, 5, 3, 5, 5]]
                      ])
tensor

<tf.Tensor: shape=(4, 2, 5), dtype=int32, numpy=
array([[[0, 5, 2, 1, 2],
        [5, 2, 1, 4, 5]],

       [[2, 3, 4, 5, 6],
        [1, 3, 3, 3, 2]],

       [[1, 1, 3, 3, 4],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [4, 5, 3, 5, 5]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensor with tf.Variable

In [ ]:
changeable_tensor = tf.Variable([10, 8])
unchangeable_tensor = tf.constant([10, 8])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 8], dtype=int32)>

### Create two random (but the same) tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (5, 4))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (5, 4))

In [ ]:
random_1

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
       [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085]],
      dtype=float32)>

In [ ]:
not_shuffled = random_1
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
       [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],
      dtype=float32)>

In [ ]:
random_3 = tf.random.Generator.from_seed(5)
Tensor = random_3.normal(shape = (3, 2, 4, 5, 2, 3))
Tensor

<tf.Tensor: shape=(3, 2, 4, 5, 2, 3), dtype=float32, numpy=
array([[[[[[ 1.0278524 ,  0.27974114, -0.01347923],
           [ 1.845181  ,  0.97061104, -1.0242516 ]],

          [[-0.6544423 , -0.29738766, -1.3240396 ],
           [ 0.28785667, -0.8757901 , -0.08857018]],

          [[ 0.69211644,  0.84215707, -0.06378496],
           [ 0.92800784, -0.6039789 , -0.1766927 ]],

          [[ 0.04221033,  0.29037967, -0.29604465],
           [-0.21134205,  0.01063002,  1.5165398 ]],

          [[ 0.27305737, -0.29925638, -0.3652325 ],
           [ 0.61883307, -1.0130816 ,  0.28291714]]],


         [[[ 1.2132233 ,  0.46988967,  0.37944323],
           [-0.6664026 ,  0.6054596 ,  0.19181173]],

          [[ 0.8045827 ,  0.4769051 , -0.7812124 ],
           [-0.996891  ,  0.33149973, -0.5445254 ]],

          [[ 1.5222508 ,  0.59303206, -0.63509274],
           [ 0.3703566 , -1.0939722 , -0.4601445 ]],

          [[ 1.5420506 , -0.16822556, -0.4390865 ],
           [-0.4129243 ,  0.35877243, 

In [ ]:
tf.random.set_seed(33)

In [ ]:
tf.random.uniform(shape = (3,3,3))

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0.33143902, 0.21867776, 0.0160141 ],
        [0.2876439 , 0.79751086, 0.21710753],
        [0.6433041 , 0.36862898, 0.50054467]],

       [[0.71634173, 0.42660952, 0.53803957],
        [0.22099257, 0.81026185, 0.57730436],
        [0.85869336, 0.3830887 , 0.10151541]],

       [[0.40971458, 0.53684866, 0.675125  ],
        [0.8787942 , 0.2530595 , 0.5888306 ],
        [0.8912947 , 0.8457856 , 0.3994583 ]]], dtype=float32)>

In [ ]:
tf.random.normal(shape = (3,3,3), stddev = 10)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ -5.7071466 ,   4.337968  ,   0.22359172],
        [  9.877345  ,   2.6069398 ,   3.8443747 ],
        [ -2.5908918 ,   3.4621825 , -12.798044  ]],

       [[-10.737386  ,  12.154512  ,   0.7009927 ],
        [ -9.368738  , -14.09329   ,   2.9389427 ],
        [ 10.775043  ,   3.0474105 ,   5.66197   ]],

       [[  1.0305743 ,  -0.15412982,   8.451374  ],
        [-13.894012  ,  -2.3528037 ,   7.9231973 ],
        [-11.1830435 , -15.409142  , -12.680808  ]]], dtype=float32)>

In [ ]:
tf.random.set_seed(50)
random_1 = tf.random.uniform(shape = (3,3,3), dtype = tf.int32, maxval = 10, seed = 50)
random_2 = tf.random.uniform(shape = (3,3,3), dtype = tf.int32, maxval = 10, seed = 50)

random_1

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[0, 0, 1],
        [7, 3, 0],
        [9, 3, 2]],

       [[0, 3, 0],
        [2, 2, 7],
        [3, 8, 6]],

       [[2, 2, 9],
        [2, 7, 1],
        [7, 1, 7]]], dtype=int32)>

In [ ]:
# tf.random.set_seed(50) # global level random seed
shuffled_1 = tf.random.shuffle(random_1, seed = 10) # operation level random seed
shuffled_2 = tf.random.shuffle(random_1, seed = 10) # operation level random seedj
print(shuffled_1)
print(shuffled_2)

tf.Tensor(
[[[0 3 0]
  [2 2 7]
  [3 8 6]]

 [[2 2 9]
  [2 7 1]
  [7 1 7]]

 [[0 0 1]
  [7 3 0]
  [9 3 2]]], shape=(3, 3, 3), dtype=int32)
tf.Tensor(
[[[0 0 1]
  [7 3 0]
  [9 3 2]]

 [[2 2 9]
  [2 7 1]
  [7 1 7]]

 [[0 3 0]
  [2 2 7]
  [3 8 6]]], shape=(3, 3, 3), dtype=int32)


### other way to make tensors

In [ ]:
  tf.ones(shape = (3,3,4), dtype = tf.int32)

<tf.Tensor: shape=(3, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [ ]:
tf.zeros(shape = [3,3,3])

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

### Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
tf.constant(numpy_A, shape = (2,2,2,3))


<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]], dtype=int32)>

 ### Getting information from tensors

 When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

Attribute     | Meaning    | Code
-----------|-----------|--------------
Shape|The length of each of the dimensions of a tensor|tensor.shape
Rank|The number of tensor dimensions.<br> - A scalar has rank 0 <br>- A vector has rank 1<br>- A matrix has rank 2<br>- A tensor has rank n| tensor.ndim
Axis or dimension|A particular dimension of a tensor|tensor[0], tensor[:, 1]...
Size|The total number of items in the tensor|tf.size(tensor)

In [ ]:
print('the ramdom_1 tensor looks like:', random_1)
print("The shape of random_1 tensor:", random_1.shape)
print('the Rank of random_1 tensor:', random_1.ndim)
print('the size of random_1 tensor:', tf.size(random_1))
print('the size of random_1 tensor:', tf.size(random_1).numpy())

the ramdom_1 tensor looks like: tf.Tensor(
[[[0 0 1]
  [7 3 0]
  [9 3 2]]

 [[0 3 0]
  [2 2 7]
  [3 8 6]]

 [[2 2 9]
  [2 7 1]
  [7 1 7]]], shape=(3, 3, 3), dtype=int32)
The shape of random_1 tensor: (3, 3, 3)
the Rank of random_1 tensor: 3
the size of random_1 tensor: tf.Tensor(27, shape=(), dtype=int32)
the size of random_1 tensor: 27


In [ ]:
random_4 = tf.random.uniform(shape=(3,2),maxval = 10, dtype = tf.int32)
random_4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 6],
       [4, 2],
       [2, 8]], dtype=int32)>

In [ ]:
 # get the first 2 elements of each dimention
 random_1[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[0, 0],
        [7, 3]],

       [[0, 3],
        [2, 2]]], dtype=int32)>

In [ ]:

random_3 = tf.random.normal(shape =[2,5,2], mean =0, stddev = 1 )
random_4 = tf.random.uniform(shape = (2,2))
random_4

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.96191144, 0.9332131 ],
       [0.33246946, 0.62886035]], dtype=float32)>

方法|関数|生成される値
----|----|---------------------
一様分布のランダム値|tf.random.uniform()|指定した範囲のランダムな実数
正規分布のランダム値|tf.random.normal()|平均・標準偏差を指定可能なランダムな実数
ランダムな整数|tf.random.uniform(shape =(),<br>maxval =None, dtype = tf.int32)<br> tf.random.randint(shape)|指定範囲のランダムな整数
再現可能なランダム値|tf.random.uniform(shape=(),seed = None)<br>tf.random.set_seed() |毎回同じ値を生成

In [ ]:
rank2_tensor = tf.constant([[10,7],
                            [3, 4]])
print(rank2_tensor.shape)
print(rank2_tensor.ndim)

(2, 2)
2


In [ ]:
print(rank2_tensor[:1, :1])

tf.Tensor([[10]], shape=(1, 1), dtype=int32)


In [ ]:
 # Add in extra dimension to rank 2 tensor
rank_3_tensor = tf.expand_dims(rank2_tensor, axis = -1)
rank_3_tensor = rank2_tensor(..., newaxis)

NameError: name 'newaxis' is not defined

In [ ]:
rank2_tensor

In [ ]:
tf.expand_dims(rank2_tensor, axis = 2)

###Manipulating Tensors(tensor operations)
**basic operations**

`+`, `-`, `*`, `/`




In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[9, 7],
                      [3, 4]])
tensor + 10

In [ ]:

# Matrix multiplication in TensorFlow
print(tensor)
print(tensor * 10)
print(tensor * tensor)

In [ ]:
tf.matmul(tensor, tensor)

In [ ]:
 Matrix1 = tf.constant([[1,2,5],
                        [7,2,1],
                        [3,3,3]])
 Matrix2 = tf.constant([[3,5],
                        [6,7],
                        [1,8]])

In [ ]:
Matrix1, Matrix2

In [ ]:
tf.linalg.matmul(Matrix1, Matrix2)
Matrix1 * Matrix2  # unable to calculate this
Matrix1 @ Matrix2  # dot product

In [ ]:
Matrix1 @ Matrix2

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions



In [ ]:
tensor1 = tf.constant([[1,2,3],
                       [4,4,4]])
tensor2 = tf.reshape(tensor1, shape = (3,2))
tensor2

In [ ]:
tensor3 = tf.transpose(tensor1)
tensor3 = tf.reshape(tensor3, shape = (2, 3))
tensor3

In [ ]:
 tf.matmul(tensor1, tensor2)

In [ ]:
tf.matmul(tensor2, tensor1)

**dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.






### Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

In [ ]:
C = tf.constant([8, 2])
C.dtype

In [ ]:
D = tf.cast(B, dtype = tf.float16)
D

In [ ]:
E = tf.cast(C, dtype = tf.float16)
E

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values


In [ ]:
# Get the absolute values
tf.abs(B)

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [71]:
# generate random tensors
rdm_tensor1 = tf.random.uniform(shape = (3,2,2,5), minval = 0, maxval = 100, dtype = tf.int32)
rdm_tensor2 = tf.random.uniform(shape = (3,2,2,5), minval = 0, maxval = 100, dtype = tf.int32)


In [72]:
print(rdm_tensor1)
print(rdm_tensor2)

tf.Tensor(
[[[[ 3 38 10 76  0]
   [ 8 70 90 48 66]]

  [[63 35  9  0 49]
   [48 59 99 79 68]]]


 [[[ 4 43 87 35 35]
   [32 76 83 95 54]]

  [[74 62 95 48  3]
   [68 28 32 52 15]]]


 [[[72 68 92 98 38]
   [ 6 50 95 38  5]]

  [[26 92 66  3 96]
   [60 28 17 61 78]]]], shape=(3, 2, 2, 5), dtype=int32)
tf.Tensor(
[[[[27 18 70 31  3]
   [23 57  8 27  4]]

  [[93 82 53 76  9]
   [17 37 23 35 98]]]


 [[[68 93 51 47 98]
   [37 35 32  3 21]]

  [[62  2 31 67 81]
   [31 39  3 76 67]]]


 [[[32 45 13 56 96]
   [23 77 66 60  0]]

  [[13  1 23 92 75]
   [59  9  9 28 86]]]], shape=(3, 2, 2, 5), dtype=int32)


In [73]:
# aggregate min and max
print(tf.reduce_min(rdm_tensor1))
print(tf.reduce_max(rdm_tensor2))

# aggregate mean and sum
print(tf.reduce_mean(rdm_tensor1))
print(tf.reduce_sum(rdm_tensor2))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(98, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(2598, shape=(), dtype=int32)


In [70]:
rdm_tensor3 = tf.random.uniform(shape = (2,2), minval = 0, maxval = 100, dtype = tf.float16)
rdm_tensor3

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[77.06, 55.97],
       [40.72, 66.1 ]], dtype=float16)>

In [ ]:
print(tf.math.reduce_variance(rdm_tensor3))
print(tf.math.reduce_std(rdm_tensor3))


### find the positional maximum and minimum

In [75]:
# create a new tensor for finding positional minimm and maximum

tf.random.set_seed(44)
F = tf.random.uniform(shape = (50,))
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.21691406, 0.7038727 , 0.28590095, 0.47886062, 0.97233224,
       0.10853219, 0.14845335, 0.48970163, 0.20112908, 0.11934876,
       0.88207614, 0.7417917 , 0.84117174, 0.88684595, 0.11674249,
       0.3902886 , 0.23854637, 0.31396985, 0.82154906, 0.2543156 ,
       0.50986934, 0.26460743, 0.07325482, 0.5148798 , 0.4464289 ,
       0.71551406, 0.23824298, 0.55751514, 0.14421296, 0.85819876,
       0.27457988, 0.07887137, 0.67671466, 0.9421835 , 0.9284011 ,
       0.75563824, 0.25915694, 0.999091  , 0.9562758 , 0.9998728 ,
       0.5068165 , 0.08749485, 0.54555345, 0.17844772, 0.340019  ,
       0.09060669, 0.6250659 , 0.4788208 , 0.7997385 , 0.9735943 ],
      dtype=float32)>

In [76]:
 # Find the positional maximum
 tf.argmax(F), F[tf.argmax(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=39>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9998728036880493>)

In [ ]:
# find the max
tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9998728036880493>

In [ ]:
tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=22>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.07325482368469238>)

In [ ]:
tf.random.set_seed(10)
G = tf.random.uniform(shape = (3,2,1,1))
G

<tf.Tensor: shape=(3, 2, 1, 1), dtype=float32, numpy=
array([[[[0.644151 ]],

        [[0.8082472]]],


       [[[0.8976548]],

        [[0.6368902]]],


       [[[0.6270969]],

        [[0.9936013]]]], dtype=float32)>

In [ ]:
# squeezeing tensors, to remove all single dimensions from a tensor
tf.squeeze(G), tf.squeeze(G).shape

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.644151 , 0.8082472],
        [0.8976548, 0.6368902],
        [0.6270969, 0.9936013]], dtype=float32)>,
 TensorShape([3, 2]))

### One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = tf.constant([0, 1, 2, 8])

tf.one_hot(some_list, 10)

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>

### Connect to GPU

select runtime tab, then change the type or runtime. Select GPU


In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Mar  5 15:25:38 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             12W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import tensorflow as tf


## TensorFlow Fundamentals challenge, exercises & extra-curriculum

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

### Exercise 1

In [99]:
vector1 = tf.constant([1, 2, 3])
scalar1 = tf.constant(5)
matrix1 = tf.constant([[2, 3, 4],
                      [5, 6, 7]])
tensor1 = tf.constant([[[1, 2],[3, 4],
                       [5, 6], [7, 8]]])

lst = list([vector1, scalar1, matrix1, tensor1])

for i in lst:
  print(i)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(
[[2 3 4]
 [5 6 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]], shape=(1, 4, 2), dtype=int32)


### Exercise 2

In [100]:
def show_result(list = None):
 for i in list:
  shape = i.shape
  rank  = i.ndim
  size = tf.size(i)
  print(f'{i}\n has shape: {shape}\n rank: {rank} \n size: {size} \n')

  show_result(list = lst)

### Excercise 3

In [101]:
rdm_tensor1 = tf.random.uniform(shape = (5, 300), minval = 0, maxval = 1)
rdm_tensor2 = tf.random.uniform(shape = (5, 300), minval = 0, maxval = 1)
rdm_tensor1, rdm_tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.33665705, 0.50275517, 0.51852036, ..., 0.24815452, 0.8902986 ,
         0.5633807 ],
        [0.8662535 , 0.91044414, 0.87681794, ..., 0.10537159, 0.0680455 ,
         0.72145736],
        [0.38240886, 0.1114316 , 0.6822984 , ..., 0.39312804, 0.6935377 ,
         0.86051595],
        [0.9631828 , 0.18857718, 0.47341454, ..., 0.6222477 , 0.01412737,
         0.28552186],
        [0.16628754, 0.4989624 , 0.9630765 , ..., 0.03409767, 0.7236476 ,
         0.2734102 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.43655777, 0.81331956, 0.9422393 , ..., 0.94322026, 0.51338005,
         0.30957866],
        [0.8613944 , 0.0439769 , 0.23754084, ..., 0.22960854, 0.8197119 ,
         0.7210922 ],
        [0.7290952 , 0.52745736, 0.51460123, ..., 0.1079644 , 0.2050153 ,
         0.16996491],
        [0.48874235, 0.752077  , 0.68108654, ..., 0.5231494 , 0.08587587,
         0.72190726],
        [0.47386

### Exercise 4

In [102]:
rdm_tensor3 = tf.transpose(rdm_tensor2)
print(rdm_tensor1 @ rdm_tensor3)


tf.Tensor(
[[79.073395 69.53318  72.409225 72.801025 78.63313 ]
 [82.94049  72.2784   77.29773  73.623436 77.34257 ]
 [75.65764  70.08681  68.722    72.65352  75.282745]
 [77.06955  73.33812  73.50906  75.082184 75.58705 ]
 [78.07422  67.47618  72.511734 72.99126  76.91411 ]], shape=(5, 5), dtype=float32)


### Exercise 5

In [103]:
print(tf.matmul(rdm_tensor1, rdm_tensor3))

tf.Tensor(
[[79.073395 69.53318  72.409225 72.801025 78.63313 ]
 [82.94049  72.2784   77.29773  73.623436 77.34257 ]
 [75.65764  70.08681  68.722    72.65352  75.282745]
 [77.06955  73.33812  73.50906  75.082184 75.58705 ]
 [78.07422  67.47618  72.511734 72.99126  76.91411 ]], shape=(5, 5), dtype=float32)


### Exercise 6

In [104]:
tf.random.set_seed(10)
rdm_tsr4 = tf.random.uniform(shape = (224, 224, 3), minval = 0, maxval = 1)
print(rdm_tsr4)

tf.Tensor(
[[[0.644151   0.8082472  0.8976548 ]
  [0.6368902  0.6270969  0.9936013 ]
  [0.02359486 0.03668392 0.5860578 ]
  ...
  [0.4021759  0.87617314 0.8240191 ]
  [0.5633031  0.2641574  0.59228563]
  [0.10286665 0.53559935 0.79840636]]

 [[0.6234499  0.56968355 0.4731779 ]
  [0.4444275  0.20357692 0.3325795 ]
  [0.6534798  0.37811399 0.11533725]
  ...
  [0.5544293  0.20996773 0.13778448]
  [0.2790662  0.652912   0.7396562 ]
  [0.30591393 0.7044697  0.74819875]]

 [[0.2532823  0.42836893 0.43761683]
  [0.00777805 0.6628947  0.01661897]
  [0.885396   0.5400171  0.06657803]
  ...
  [0.79703116 0.8331604  0.05939698]
  [0.6077355  0.30967402 0.55589724]
  [0.4235295  0.61563694 0.53281474]]

 ...

 [[0.39041972 0.29344285 0.6998919 ]
  [0.46327806 0.47750676 0.822955  ]
  [0.4131173  0.22308564 0.4960394 ]
  ...
  [0.4231714  0.31755304 0.9184462 ]
  [0.08461833 0.9147731  0.33426833]
  [0.3445344  0.54825485 0.9886668 ]]

 [[0.33098423 0.59955263 0.08384907]
  [0.4182707  0.71565986 0

### Exercise 7

In [105]:
print(f'min value: {tf.math.reduce_min(rdm_tsr4)}')
print(f'max value: {tf.math.reduce_max(rdm_tsr4)}')

min value: 1.919269561767578e-05
max value: 0.9999773502349854


### Exercise 8

In [106]:
rdm_tsr5 = tf.random.uniform(shape = (1, 244, 244, 3))
rdm_tsr5.shape

TensorShape([1, 244, 244, 3])

In [107]:
tf.squeeze(rdm_tsr5).shape

TensorShape([244, 244, 3])

### Exercise 9

In [108]:
rdm_tsr6 = tf.constant([4, 10, 4, 5, 1, 59, 6, 19, 25, 44])
rdm_tsr6

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 4, 10,  4,  5,  1, 59,  6, 19, 25, 44], dtype=int32)>

In [109]:
tf.argmax(rdm_tsr6)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [110]:
rdm_tsr6[tf.argmax(rdm_tsr6)]

<tf.Tensor: shape=(), dtype=int32, numpy=59>

### Exercise 10

In [115]:
tf.one_hot(rdm_tsr6, depth = 11)

<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>